### ISSUE TITLE
General check

### ISSUE THREAD

**Issue by Charlyzzz** [Charlyzzz/rouge#1]
Rack it up, hit `:9292/wollok` and let me know what you think @flbulgarelli
You can play with different themes `:9292/wollok?theme=$theme_name`

Themes: 
-  base16
- colorful
- github
- gruvbox
- molokai
- monokai
- monokai_sublime
- thankful_eyes
- tulip

**Comment by flbulgarelli** [comment]
Nice work!

I see some inconsistencies in the way we are rendering the variables: the lexer is messing up local variables, attributes and parameters - see the `Content` constructor in the sample code. To avoid problems, I would simply use `Name` or `Name.Other` in three scenarios.

**Comment by flbulgarelli** [comment]
Also, I'd like to find some way of having a different color for `self` in the github theme.

**Comment by Charlyzzz** [comment]
Roger that.

You can extend that theme and change the value

**Comment by flbulgarelli** [comment]
I was think in something like not extending the theme, but finding a lexeme that has a different color and still matches the `self` semantic

**Comment by Charlyzzz** [comment]
> To avoid problems, I would simply use Name or Name.Other in three scenarios.

Didn't you wanted to differentiate objects and messages?. It's up to us to decide if objects should be colorized (my choice) or messages.

The difference in colors was on purpose, but it's possible to unify them.

**Comment by flbulgarelli** [comment]
> Didn't you wanted to differentiate objects and messages?. It's up to us to decide if objects should be colorized (my choice) or messages.

The difference between objects and messages is OK. What I am proposing here is to not make any distinction between local variables, parameters and attributes. Since in wollok self is mandatory, there is not ambiguity among them and messages, right?

**Comment by Charlyzzz** [comment]
Damn right! My bad

**Comment by Charlyzzz** [comment]
New version! Expecting your opinion 😄
